### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by stefan-balke** [libsndfile/libsamplerate#1]
Hi Erik,

thanks for this great lib!

I'd like to make it easier to ship with tools like anaconda and python.

It would be nice, if you could tag the commit which represents the current version
so that I can refer to it while building.

Thanks Stefan

**Comment by erikd** [comment]
I intend to tag all future releases. Thanks.

**Comment by bradleysepos** [comment]
Nice to see active development on GitHub, @erikd. 👍 

Any chance you intend to tag and release 1.10 soon? We could use the GCC 7 commit(s) in another project but its build system will require a release tag. Thanks.

**Comment by bradleysepos** [comment]
@erikd Any reason not to tag a release on current master head?

**Comment by bradleysepos** [comment]
Kind poke. The lack of release tagging continues to present an issue for downstream projects.

**Comment by kloczek** [comment]
+1

**Comment by kloczek** [comment]
BTW: any plans to make new release?

**Comment by evpobr** [comment]
We have signed tags now. Closing this.
