### ISSUE TITLE
cmake: cpack picks wrong version number

### ISSUE THREAD

**Issue by sezero** [libsndfile/libsamplerate#135]
As noted in title:  `make package_source` with cmake generates `libsamplerate-0.1.1-Source.tar.gz`
Notice `0.1.1` instead of current `0.1.9`. I don't know if this facility is actually meant to be used
but still.. This is with cmake-3.9.6.

**Comment by evpobr** [comment]
I guess it is my bug. CMake < 3.12 will not use PROJECT_VERSION variables to set CPACK_PACKAGE_VERSION.
