### ISSUE TITLE
BUILD SHARED_LIBS and CMAKE_BUILD_TYPE menus not available with cmake-gui

### ISSUE THREAD

**Issue by sezero** [libsndfile/libsamplerate#136]
Is that intentional? Maybe you need something like the following in CMakeLists.txt?
```
IF (NOT DEFINED CMAKE_BUILD_TYPE OR CMAKE_BUILD_TYPE STREQUAL "")
    MESSAGE(STATUS "Setting build type to 'Debug' as none was specified.")
    SET(CMAKE_BUILD_TYPE Debug CACHE STRING "Choose the type of build." FORCE)
    SET_PROPERTY(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
ENDIF ()
SET(CMAKE_CONFIGURATION_TYPES "${CMAKE_BUILD_TYPE}")
MESSAGE(STATUS "Build Type: ${CMAKE_BUILD_TYPE}")

OPTION(BUILD_SHARED_LIBS "Build dynamic library" OFF)
```

**Comment by evpobr** [comment]
Probably Yes for `BUILD_SHARED_LIBS`, but I'm not sure about `CMAKE_BUILD_TYPE`. In fact, an empty `CMAKE_BUILD_TYPE` will allow you to pass `-O2` instead of `-O3` by default, for example.

**Comment by sezero** [comment]
> Probably Yes for `BUILD_SHARED_LIBS`, but I'm not sure about `CMAKE_BUILD_TYPE`. In fact, an empty `CMAKE_BUILD_TYPE` will allow you to pass `-O2` instead of `-O3` by default, for example.

You do what you do from cmdline, and that's good, but gui users (e.g. windows users) won't be doing that.

**Comment by evpobr** [comment]
I don't know what the point is now to use cmake-gui on Windows, if you can just open the CMake project folder in Visual Studio or VS Code. Everything is automatically configured and managed via the IDE.

**Comment by sezero** [comment]
Well, I have no strong opinions on the case - just notified you of the issue.

**Comment by evpobr** [comment]
Ok, let's leave as it is.
