### ISSUE TITLE
semantic versioning regression: `0.1.8` followed by `0.1.0`

### ISSUE THREAD

**Issue by umlaeute** [libsndfile/libsamplerate#140]
Debian/buster (currently "stable") ships with `libsamplerate0_0.1.9-2`, which includes a dynamic library file:

    /usr/lib/x86_64-linux-gnu/libsamplerate.so.0.1.8

compiling the latest and greatest libsamplerate-0.2.0 i get a file:

    /usr/lib/x86_64-linux-gnu/libsamplerate.so.0.1.0

This decrements the *micro* release, which is plain wrong!!

the new libsamplerate also introduces a new symbol `src_clone`, which would - according to semantic versioning - warrants a:
- reset of the *micro* version to *0*
- increment of the *minor* version to *2*

please fix this and make a bugfix release asap.

**Comment by umlaeute** [comment]
i *guess* the [proper way](https://autotools.io/libtool/version.html#idm46482193960416) to calculate the `SHARED_VERSION_INFO` from the package version (assuming that the package version follows the semantic versioning for the library) is:

~~~sh
CLEAN_VERSION=$(echo $PACKAGE_VERSION | $SED "s/p.*//")
VERSION_MAJOR=$(echo $CLEAN_VERSION   | $SED "s/\..*//")
VERSION_MINOR=$(echo $CLEAN_VERSION   | $SED "s/.*\.\(.*\)\..*/\1/")
VERSION_BUGFIX=$(echo $CLEAN_VERSION  | $SED "s/.*\.//")

SHARED_VERSION_INFO="$((VERSION_MAJOR+VERSION_MINOR)):${VERSION_BUGFIX}:${VERSION_MINOR}"
~~~

or (using `cut` rather than `sed`):
~~~sh
CLEAN_VERSION=$(echo $PACKAGE_VERSION | $SED "s/p.*//")
VERSION_MAJOR=$(echo $CLEAN_VERSION   | cut -f1 -d.)
VERSION_MINOR=$(echo $CLEAN_VERSION   | cut -f2 -d.)
VERSION_BUGFIX=$(echo $CLEAN_VERSION  | cut -f3 -d.)

SHARED_VERSION_INFO="$((VERSION_MAJOR+VERSION_MINOR)):${VERSION_BUGFIX}:${VERSION_MINOR}"
~~~

**Comment by evpobr** [comment]
@SoapGentoo , we failed a little.

**Comment by evpobr** [comment]
@umlaeute , yep we have a bug. Is minor release fixing this ok?

**Comment by evpobr** [comment]
@umlaeute , CMake works.

**Comment by SoapGentoo** [comment]
@evpobr we should just switch to manually maintaining the libtool versioning. I will prepare a PR.

**Comment by evpobr** [comment]
I absolutely agree with you.

**Comment by umlaeute** [comment]
@evpobr a minor release would be splendid.

i haven't tested `CMake`, as the README says to use `configure` (and mentions `CMake` only as the *new alternative*)

since Debian is currently nearing freeze (the first stage already started), it would be great if you could put out a bugfix release very soon.

**Comment by SoapGentoo** [comment]
We should get our a release today, I'm working on it

**Comment by SoapGentoo** [comment]
I'll add the release manager info before cutting the release

**Comment by evpobr** [comment]
@SoapGentoo , don't forget to bump API version too, And to sign release tag.

**Comment by SoapGentoo** [comment]
We're already at `0.2.1`? I bump the version after every released cut

**Comment by evpobr** [comment]
Oh, i forgot that.

**Comment by evpobr** [comment]
> We're already at `0.2.1`? I bump the version after every released cut

@SoapGentoo , hmm, do we really need that post release bump? It is weird to see 'This is version 0.2.1' when we released '0.2.0' only. As for me, before actual release, even beta, it is '0.2.0' with patches.

**Comment by SoapGentoo** [comment]
sure, I can also skip the post-release bump.

**Comment by SoapGentoo** [comment]
ok, `0.2.1` has been cut, @evpobr let me know when the Windows artifacts are available

**Comment by evpobr** [comment]
@SoapGentoo , here they are:

[libsamplerate-0.2.1-win32.zip](https://github.com/libsndfile/libsamplerate/files/5861610/libsamplerate-0.2.1-win32.zip)
[libsamplerate-0.2.1-win64.zip](https://github.com/libsndfile/libsamplerate/files/5861611/libsamplerate-0.2.1-win64.zip)


BTW release tag is unsigned :smile:

**Comment by evpobr** [comment]
@SoapGentoo , thanks for fast fix.

**Comment by evpobr** [comment]
@Be-ing , whould you like to update Vcpkg port?

**Comment by Be-ing** [comment]
> @evpobr we should just switch to manually maintaining the libtool versioning. I will prepare a PR.

I disagree. I highly recommend removing all build systems besides CMake. You *will* have bugs like this that only affect one build system if you try to maintain redundant build systems.

**Comment by evpobr** [comment]
@Be-ing , check #134.

**Comment by Be-ing** [comment]
If CMake works fine, there's no need to update vcpkg, is there?

**Comment by evpobr** [comment]
Yes, CMake build works as it should. But we have a new version of the library and to avoid unnecessary questions it is worth updating the port.

**Comment by SoapGentoo** [comment]
@evpobr whoops, I've signed the `0.2.0` and `0.2.1` tags now, and uploaded your tarballs

**Comment by Be-ing** [comment]
Is it possible to add an additional signature to a Git tag after it is made?

**Comment by SoapGentoo** [comment]
nope, the only way to do it is to delete the tag, and create a new signed one, and force push over it (which I've done)

**Comment by Be-ing** [comment]
Tags should never be deleted after pushing. If they are, it is a hassle for everyone who has cloned the repo.
