### ISSUE TITLE
MinGW build produces warnings 

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsamplerate#154]
[build] [6/61   1% :: 0.547] Building C object src/CMakeFiles/samplerate.dir/src_zoh.c.obj
    [build] ../src/src_zoh.c: In function 'zoh_get_name':
    [build] ../src/src_zoh.c:154:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
    [build]   154 | } /* zoh_get_name */
    [build]       | ^

https://stackoverflow.com/questions/7994415/mingw-fvisibility-hidden-does-not-seem-to-work

**Comment by SoapGentoo** [comment]
@evpobr I havent looked into how you detect visibility support in CMake

**Comment by evpobr** [comment]
Hmm, didn't you add this code?

**Comment by SoapGentoo** [comment]
yano, I added the macros, @sezero added the detection machinery. @sezero ideas?

**Comment by evpobr** [comment]
```c
#ifndef _WIN32
...
#endif
```

**Comment by SoapGentoo** [comment]
...wasn't the whole point of the [bikeshed](https://github.com/libsndfile/libsamplerate/pull/151#discussion_r575958701) to specifically avoid platform-specific macros?

**Comment by sezero** [comment]
gcc-4.5 rejects the visibility checks, but gcc-7.5 seems like it does not
(which are the mingw cross-toolchains I have access to.)

**Comment by sezero** [comment]
> Just define to nothing for Windows. Nothing is exported from DLL by default.

Indeed: I tried -Werror=attributes in configury, didn't help (Don't know why,
it's not impossible that I made a mistake there, though.)

Lazy+easy solution would be something like the following:
```diff
diff --git a/src/common.h b/src/common.h
index 03f344b..d027d41 100644
--- a/src/common.h
+++ b/src/common.h
@@ -16,6 +16,9 @@
 
 #include <math.h>
 
+#ifdef _WIN32
+  #undef HAVE_VISIBILITY
+#endif
 #if HAVE_VISIBILITY
   #define LIBSAMPLERATE_DLL_PRIVATE __attribute__ ((visibility ("hidden")))
 #elif defined (__APPLE__)
```

**Comment by evpobr** [comment]
> > Just define to nothing for Windows. Nothing is exported from DLL by default.
> 
> Indeed: I tried -Werror=attributes in configury, didn't help (Don't know why,
> it's not impossible that I made a mistake there, though.)
> 
> Lazy+easy solution would be something like the following:
> 
> ```diff
> diff --git a/src/common.h b/src/common.h
> index 03f344b..d027d41 100644
> --- a/src/common.h
> +++ b/src/common.h
> @@ -16,6 +16,9 @@
>  
>  #include <math.h>
>  
> +#ifdef _WIN32
> +  #undef HAVE_VISIBILITY
> +#endif
>  #if HAVE_VISIBILITY
>    #define LIBSAMPLERATE_DLL_PRIVATE __attribute__ ((visibility ("hidden")))
>  #elif defined (__APPLE__)
> ```

Yep it works.

**Comment by sezero** [comment]
> Yep it works.

OK then, just apply (I don't intend creating a pull-request for it.)
