### ISSUE TITLE
cmake error with a cross-toolchain file

### ISSUE THREAD

**Issue by sezero** [libsndfile/libsamplerate#162]
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- Checking for module 'sndfile'
--   Found sndfile, version 1.0.20
-- Checking processor clipping capabilities...
-- Checking processor clipping capabilities... disabled
-- Performing Test HAVE_VISIBILITY
-- Performing Test HAVE_VISIBILITY - Failed
-- Looking for sys/times.h
-- Looking for sys/times.h - not found
-- Looking for alarm
-- Looking for alarm - found
-- Looking for signal
-- Looking for signal - found
-- Looking for SIGALRM
-- Looking for SIGALRM - not found
-- Checking for module 'fftw3'
--   No package 'fftw3' found
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
-- Configuring done
CMake Error at tests/CMakeLists.txt:88 (add_executable):
  Target "src-evaluate" links to target "PkgConfig::SndFile" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/CMakeLists.txt:14 (add_executable):
  Target "timewarp-file" links to target "PkgConfig::SndFile" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at examples/CMakeLists.txt:20 (add_executable):
  Target "varispeed-play" links to target "PkgConfig::SndFile" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
-- Build files have been written to: XXX
```

It does report errors, but it does generate the makefiles..
The toolchain file in question is this:
```
SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-windres)

SET(CMAKE_FIND_ROOT_PATH /opt/cross_win64 /opt/cross_win64/x86_64-w64-mingw32)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

I did not setup a cross-pkgconfig, can it be the reason? (Don't know how but..)

**Comment by sezero** [comment]
BTW, this is with cmake-3.9.6 and cmake-3.11.2.

**Comment by evpobr** [comment]
> ```
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
> -- Checking for module 'sndfile'
> --   Found sndfile, version 1.0.20
> -- Checking processor clipping capabilities...
> -- Checking processor clipping capabilities... disabled
> -- Performing Test HAVE_VISIBILITY
> -- Performing Test HAVE_VISIBILITY - Failed
> -- Looking for sys/times.h
> -- Looking for sys/times.h - not found
> -- Looking for alarm
> -- Looking for alarm - found
> -- Looking for signal
> -- Looking for signal - found
> -- Looking for SIGALRM
> -- Looking for SIGALRM - not found
> -- Checking for module 'fftw3'
> --   No package 'fftw3' found
> -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
> -- Configuring done
> CMake Error at tests/CMakeLists.txt:88 (add_executable):
>   Target "src-evaluate" links to target "PkgConfig::SndFile" but the target
>   was not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> CMake Error at examples/CMakeLists.txt:14 (add_executable):
>   Target "timewarp-file" links to target "PkgConfig::SndFile" but the target
>   was not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> CMake Error at examples/CMakeLists.txt:20 (add_executable):
>   Target "varispeed-play" links to target "PkgConfig::SndFile" but the target
>   was not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> -- Generating done
> -- Build files have been written to: XXX
> ```
> 
> It does report errors, but it does generate the makefiles..
> The toolchain file in question is this:
> 
> ```
> SET(CMAKE_SYSTEM_NAME Windows)
> 
> SET(CMAKE_C_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-gcc)
> SET(CMAKE_CXX_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-g++)
> SET(CMAKE_RC_COMPILER /opt/cross_win64/bin/x86_64-w64-mingw32-windres)
> 
> SET(CMAKE_FIND_ROOT_PATH /opt/cross_win64 /opt/cross_win64/x86_64-w64-mingw32)
> 
> SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
> SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
> SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
> ```
> 
> I did not setup a cross-pkgconfig, can it be the reason? (Don't know how but..)

I guess so.

**Comment by sezero** [comment]
With autotools, I can set pkg-config path by setting `PKG_CONFIG_PATH`
environment variable, or I can disable pkg-config functionality altogether
by setting `PKG_CONFIG` to `/bin/false`. Is there a similar way to do so
with cmake?

If I am to setup a corss-pkgconfig, how should I tell set it up in my
toolchain file, i.e. what is the cmake variable name for it?

**Comment by evpobr** [comment]
> With autotools, I can set pkg-config path by setting `PKG_CONFIG_PATH`
> environment variable, or I can disable pkg-config functionality altogether
> by setting `PKG_CONFIG` to `/bin/false`. Is there a similar way to do so
> with cmake?

`FindPkgConfig` is just wrapper around of `pkg-config`, i guess you can use all the same tricks. Also you can try [`PKG_CONFIG_EXECUTABLE`](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html).

**Comment by sezero** [comment]
OK thanks. Closing this one.
