### ISSUE TITLE
src_process returns less samples than requested if the rate recently changed

### ISSUE THREAD

**Issue by mbacarella** [libsndfile/libsamplerate#171]
I noticed audio that I was filtering through libsamplerate would stutter a bit right after a sample rate change. It was because process was producing slightly fewer samples than requested, so my audio playback buffer wasn't being completely filled.

I looked around at toy programs that use libsamplerate and saw that some of them add 64 to the input_frames after computing the ratio of input_frames. 

When I add 64 to input_frames in my program it stops stuttering as well. What behavior is this relying on?

**Comment by evpobr** [comment]
Hi @mbacarella . II think the clue is hiding here: <http://libsndfile.github.io/libsamplerate/faq.html#Q006>.

**Comment by mbacarella** [comment]
Well that indeed solves the mystery. I was not aware there was a FAQ. Thank you!

**Comment by evpobr** [comment]
You're welcome.
