### ISSUE TITLE
No anti-aliasing filter for linear resampling

### ISSUE THREAD

**Issue by jpaasen** [libsndfile/libsamplerate#182]
There is no anti-aliasing filter applied for the Linear resampling mode.

So if you create the following chirp:

![chirp_stft_targetfs_48000_nmels256_hop480_win1024_fft1024_stft_targetfs48000_hop480_win1024_fft1024](https://user-images.githubusercontent.com/1258637/203947616-322600f3-5cbf-4d0f-9637-496101e84587.jpg)

and you resample (down) with `Linear` you get:

![chirp_stft_targetfs_16000_nmels256_hop160_win1024_fft1024_stft_targetfs16000_hop160_win1024_fft1024](https://user-images.githubusercontent.com/1258637/203947716-a7efa020-16b4-4c66-95c3-648ce35ae4f7.jpg)

This might be intentional, but it is not straightforward from the documentation that this is the case. 

The documentation says:

```
SRC_SINC_FASTEST - This is the fastest bandlimited interpolator and has an SNR of 97dB and a bandwidth of 80%.
SRC_ZERO_ORDER_HOLD - A Zero Order Hold converter (interpolated value is equal to the last value). The quality is poor but the conversion speed is blindlingly fast.
SRC_LINEAR - A linear converter. Again the quality is poor, but the conversion speed is blindingly fast.
```

The line `This is the fastest bandlimited interpolator` for `SRC_SINC_FASTEST` implies that the latter two options are not band-limited.

The documentation could be improved with a line or two, stating the latter two options should NOT be used without the user taking care of the anti-aliasing filtering him/herself.

If you downsample using `SRC_SINC_FASTEST`. `libsamplerate` takes care of the anti-aliasing filtering:
![chirp_sinc_fastest_stft_targetfs_16000_nmels256_hop160_win1024_fft1024_stft_targetfs16000_hop160_win1024_fft1024](https://user-images.githubusercontent.com/1258637/203948476-be8abd4c-18b1-4db5-bd2f-cdaa91bd64fe.jpg)

**Comment by evpobr** [comment]
Hi @jpaasen . Pull request?

**Comment by jpaasen** [comment]
I can do a PR with improvements to the doc. I just wanted to establish if this behavior was intentional or not.

Looking at [librosa.resample](https://librosa.org/doc/main/_modules/librosa/core/audio.html#resample), that exposes `libsamplerate` for some of its supported `res_type` values, there are no warnings about using ‘linear’ for down-sampling. So the misconception seems "widespread".

**Comment by evpobr** [comment]
We need to ask @erikd. But he doesn't answer.

**Comment by erikd** [comment]
The linear sample rate converter is provided for completeness and for something to compare actually good converted against.

If you want sample rate conversion without aliasing, then used the `SRC_SINC_*` converters.

**Comment by evpobr** [comment]
Hi @erikd :smile:
