### ISSUE TITLE
Libsamplerate as fractional sample rate converter ?

### ISSUE THREAD

**Issue by 79rpm** [libsndfile/libsamplerate#186]
Would you confirm that some of the API offered by the libsamplerate can be used to do fractional sample rate conversion. Thank you.

**Comment by aloiscochard** [comment]
The issue tracker is not a place to ask question.

You can read the following on the official website:
"Arbitrary in this case means that the ratio of input and output sample rates can be an irrational number."

**Comment by 79rpm** [comment]
Thanks @aloiscochard
