### ISSUE TITLE
Varispeed but preserve pitch

### ISSUE THREAD

**Issue by Castor215** [libsndfile/libsamplerate#200]
I am trying to implement libsamplerate in an emulator. What I want is for the audio to increase duration when the emulator slows down but preserve pitch. What is happening is that the audio gets lower in pitch when the emulator slows down, which sounds dreadful.

Is it possible to stretch the audio in this way?

**Comment by erikd** [comment]
If you want to vary the speed without varying the pitch, you need a time stretching library. Sorry `libsamplerate` does not do what you want.

> Is it possible to stretch the audio in this way?

Yes, but not with this library.
