### ISSUE TITLE
typo in libsamplerate/docs/api_full.md

### ISSUE THREAD

**Issue by aholzinger** [libsndfile/libsamplerate#202]
In the very last section "Set Ratio" we read

> When using the src_process or src_callback_process APIs and updating the src_ratio field of the SRC_STATE struct

To my knowledge the SRC_STATE struct does **not** hold a src_ratio field.

I guees the SRC_DATA struct was meant.

**Comment by evpobr** [comment]
Hi @aholzinger . Pull request?

**Comment by luzpaz** [comment]
how would you re-word this then ?

**Comment by aholzinger** [comment]
When using the src_process or src_callback_process APIs and updating the src_ratio field of the SRC_DATA struct
