### ISSUE TITLE
Int16 support?

### ISSUE THREAD

**Issue by alexey-v-paramonov** [libsndfile/libsamplerate#215]
I do all my audio processing as `int16`, is it possible to make `libsamplerate` work without the need to multiply/divide by 32768 for float conversion? If there is a fork or an alternative library for int processing - let me know.

Functions `src_int_to_float_array` `src_float_to_int_array` really help, but maybe there is a way not to use that extra step to save some CPU?

**Comment by erikd** [comment]
Doing your processing on `int16` sounds so 1990s to me.

Slowest grade machines less than 10 years old have more than enough memory and CPU power to process floats.

**Comment by alexey-v-paramonov** [comment]
Well, I get my `int16`s from another program as source audio so I can not do much about it.

**Comment by erikd** [comment]
> Well, I get my `int16`s from another program as source audio so I can not do much about it.

So convert them once on the way into you app and once on the way out. Dealing with floats in audio processing is orders of magnitude easier than dealing with `int16`. All of the big name audio processing programs have operated on floats or doubles for well over a decade.

**Comment by alexey-v-paramonov** [comment]
Thanks, will do.

**Comment by erikd** [comment]
Please close this if you are happy with the outcome.

**Comment by midn1** [comment]
> Doing your processing on int16 sounds so 1990s to me.

Who asked?

IOW, int16 isn't supported because the authors would rather chase trends than write quality software.
