### ISSUE TITLE
The autoconf in 0.1.9 dose not support aarch64

### ISSUE THREAD

**Issue by manszigher** [libsndfile/libsamplerate#66]
The config.sub and config.guess should be updated to include aarch64 in 0.1.9 since I cannot see that these files are included in the repo I guess they are copied from somewhere. When looking through my host machine I located them under /usr/share/misc and they do include aarch64.

**Comment by manszigher** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734673

**Comment by manszigher** [comment]
I solved it by copying the files from my host under /usr/share/misc not sure if this is the best way to do it but it worked for me. It appears as if this was solved when packaging the debian package.

**Comment by dbogdanov** [comment]
I have a similar issue, trying to compile for Android.

**Comment by SoapGentoo** [comment]
Is this still applicable? `0.2.1` has been signed with a very recent version of Autoconf with updated `config.sub` and `config.guess`.
