### ISSUE TITLE
Deprecated Visual Studio Code building

### ISSUE THREAD

**Issue by Minabsapi** [libsndfile/libsamplerate#96]
Hello,
I tried to make the files following the instructions [here](https://raw.githubusercontent.com/erikd/libsamplerate/master/doc/win32.html)
However it doesn't work, providing a modern VC path seems to give troubles. 
Tried to modify the PROG_LINK_FLAGS variable by fixing manually some headers (it couldn't find `stdio.h` for instance, so I provided it from MinGW), but it doesn't seem to recognize it.
Isn't there a more modern way to build all this ?

**Comment by erikd** [comment]
I have not used Windows for over a decade. There is a CMake build system in Git but I have zero idea of how to use that the build on Windows.

**Comment by Minabsapi** [comment]
I see... Well, isn't there any way to cross-compile it at least ? (I know it's not on the README, so if any I expect it to be hacky)

**Comment by erikd** [comment]
Cross compile from Linux? That should certainly be possible, and while I have done it for other projects, I have not done it for this one.

**Comment by moebiussurfing** [comment]
hey @Minabsapi , @erikd,  I am not sure could be related to this issue... 
but any idea of how can I solve these errors?
https://github.com/adamstark/BTrack/issues/14

**Comment by erikd** [comment]
That is valid C code. If you are compiling it with a C++ compiler you may get warnings on valid C code.

**Comment by moebiussurfing** [comment]
ok. Thanks!
Just bypassed all the errors doing casting:
`if ((filter = (SINC_FILTER *) calloc (1, sizeof (SINC_FILTER) + sizeof (filter->buffer [0]) * (temp_filter.b_len + temp_filter.channels))) == NULL) `
NOw having other issues but on BTrack..

**Comment by erikd** [comment]
Casting is the way to fix it in C++, but in C, casting like that can hide type errors.

**Comment by evpobr** [comment]
With CMake project this issue is outdated. Closing now.
